<?php $_code = $this->getMethodCode() ?>
<ul class="form-list" id="payment_form_<?php echo $_code ?>" style="display:none;">
  <li>
    <label for="<?php echo $_code ?>_payment_method" class="required"><em>*</em><?php echo $this->__('Select one method') ?></label>
    <div class="input-box">
      <select id="<?php echo $_code ?>_payment_method" name="payment[alepay_method]">
        <?php if ($this->getMethod()->getConfigData('payment_normal_active') === '1'): ?>
        <option><?php echo $this->getMethod()->getConfigData('payment_normal_label') ?></option>
        <?php endif; ?>
        <?php if ($this->getMethod()->getConfigData('payment_installment_active') === '1'): ?>
        <option><?php echo $this->getMethod()->getConfigData('payment_installment_label') ?></option>
        <?php endif; ?>
        <?php if ($this->getMethod()->getConfigData('payment_token_active') === '1'): ?>
        <option><?php echo $this->getMethod()->getConfigData('payment_token_label') ?></option>
        <?php endif; ?>
      </select>
    </div>
  </li>
</ul>
<?php //echo $this->htmlEscape($this->getInfoData('payment_normal'))
//var_dump($this->getMethod()->getConfigData('env')); 
?>
